currency: EMERALD
default-class: Warrior
linear-experience: false
remove-item-delay: 120
disable-worlds:
  - world_nether
  - world_the_end
firework: true
exp-loss-on-death: 25
enable-spells: true
mob-spawn-time: 15
disable-mic: false